FROM nginx

ENV WORKDIR /usr/share/nginx/html
ENV PACKAGE  sb_dist/
ENV NGINXCONFIG nginx.basicdata.conf
ENV NGINXCONFIG_DIR  /etc/nginx/conf.d/
RUN  ls -hl

WORKDIR $WORKDIR
COPY $PACKAGE .

WORKDIR $NGINXCONFIG_DIR
COPY  $NGINXCONFIG .
